### ISSUE TITLE
Benefit of Keeping Service's and Repository's Interface separate.

### ISSUE THREAD

**Issue by Kjaer** [bailabs/react_js_clean_architecture#11]
`Domain` layer keeps the `Services` and `Repository Interfaces`. But in the end, all the `Repository Implementations` in the `Data` layer, have to implement `Service`'s interface (via Repository Interface) in order to provide Service's behaviour consistent.

So can you elaborate what are the advantages keeping `Repository Interface` separate from `Service`'s Interface?

**Comment by iRaySpace** [comment]
Hello,

From what I have understood from your question, you asked why there is a need to have separate usecases from repositories, right?

The reason for this one is on the `README.md`

```
- Usecases
--> Application-specific business rules
--> Encapsulate all the usecases of the application
--> Orchestrate the flow of data throughout the app
--> Should not be affected by any UI changes whatsoever
--> Might change if the functionality and flow of application change

- Repositories
--> Abstract classes that define the expected functionality of outer layers
--> Are not aware of outer layers, simply define expected functionality
--> E.g. The Login usecase expects a Repository that has login functionality
--> Passed to Usecases from outer layers
```

Let's say you have an Sales Transaction CRUD and Firebase repository.

If repositories and usecases are not separated, that would mean CRUD operation and validation are on repository.

We have the following functions on the repository:
- Validate for Sales
- Save it Firebase

The problem starts when you want to do a Returns on Sales Transaction.
- Make a copy of existing Sales Transaction
- Mark it as a Credit Note and make items' qty negative.
 
How do we manipulate existing data? 
By adding another set of operations to the repository?
...
Now, what if we want to make another repository for local storage (offline) purposes together with Firebase? 
We need to implement those operations on the local storage repository again.

Or, in place of `usecases`, we manipulate the data from the `app`
...
What if we want to migrate to another UI from `React` to `Vue`?

There are many ways to handle the problem, but the `Clean Architecture` proposes having usecases. When you have usecases, you can delegate data manipulation / validation without having to touch the repository.

As much as possible, any business logic will be separated from the other layers.

Regards,

Ivan
